### PR TITLE
Created scToNeb.R and updated README

### PR DESCRIPTION
**Pull request by Raghav1881**
Created function to convert Seurat/SingleCellExperiment objects into the format used within the nebula vignette

### CODE REVIEW

**Review by lhe17 — COMMENTED** [review]
Thank you very much, Raghav1881.
I am currently during a relocation. I'll get back to you once I finish the review of your contribution in a few weeks. Also please send me your full name and email address so that I can add them to the updated version.
Best regards,
Liang

**Review by lhe17 — COMMENTED** [review]
Hi Raghav1881,

I have two questions about the function you create.
The name of the function is scToNeb, but why does it become seu_to_neb when you use it in the example and vignette?
The second question is that you use an example data 'seurat_object.rds'. Can you share such a data set that can be incorporated into the package. Otherwise, I can create an example Seurate object.

Best regards,
Liang

**Comment by Raghav1881** [comment]
Hi Liang,

My full name is Raghav Sharma and email address is raghavv.sharma@mail.utoronto.ca. I initially created the function with the intention of converting Seurat objects hence the name seu_to_neb, but I have edited all instances of it now.

For the sample dataset, would you like an actual single cell Seurat dataset (contains actual gene names, UMIs), or one I generate that doesn't contain those features. Either option is fine by me, let me know if you have a preference.

Best,
Raghav

**Comment by lhe17** [comment]
Hi Raghav,

Thank you.
I prefer an actual single cell Seurat dataset.
I'll incorporate your contribution in the next version.

Best regards,
Liang

**Comment by Raghav1881** [comment]
Hi Liang, 

I added a publicly available dataset within the pull request, and updated some of the package documentation to work with this object. I also added the citation for the object to references.bib. 

Best,
Raghav

**Comment by lhe17** [comment]
Hi Raghav,
Thank you again for your contribution.
I'm going to merge your branch and incorporate it in the upcoming version (v1.5.0) of NEBULA. I'll make some modifications to the example data you provide. Basically, I will reduce the file size by selecting the first 1000 genes because some repository does not allow such a large data file. I'm still testing the program and I'll let you know if I find any other bugs in your R script.
Best regards,
Liang

**Pull request merged**
